export const memberConstants = {
  TREE_REQUEST: 'TREE_REQUEST',
  TREE_SUCCESS: 'TREE_SUCCESS',
  TREE_FAILURE: 'TREE_FAILURE',

  MEMBER_TREE_REQUEST: 'MEMBER_TREE_REQUEST',
  MEMBER_TREE_SUCCESS: 'MEMBER_TREE_SUCCESS',
  MEMBER_TREE_FAILURE: 'MEMBER_TREE_FAILURE'
}